backend:
  # name: git-gateway
  name: proxy
  proxy_url: http://localhost:8081/api/v1
  branch: master
media_folder: public/images
public_folder: /images
# publish_mode: editorial_workflow

collections:
  - name: "config"
    label: "Config"
    delete: false
    editor:
      preview: false
    files:
      - name: "general"
        label: "Site Config"
        file: "config.json"
        description: "General site settings"
        fields:
          - label: "URL"
            name: "base_url"
            widget: "string"
            hint: "Do not enter the trailing slash of the URL"
          - label: "Site title"
            name: "site_title"
            widget: "string"
          - label: "Site description"
            name: "site_description"
            widget: "string"
          - label: "Site keywords"
            name: "site_keywords"
            widget: "list"
            summary: "{{fields.keyword.keyword}}"
            field:
              label: Keyword
              name: keyword
              widget: "string"
          - label: "Twitter account"
            name: "twitter_account"
            widget: "string"
          - label: "GitHub account"
            name: "github_account"
            widget: "string"

  - name: "meta"
    label: "Meta"
    delete: false
    editor:
      preview: false
    files:
      - name: "authors"
        label: "Authors"
        file: "meta/authors.yml"
        description: "Author descriptions"
        fields:
          - name: authors
            label: Authors
            label_singular: "Author"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the author"
              - label: "Name"
                name: "name"
                widget: "string"
                hint: "First and Last"
              - label: "Introduction"
                name: "introduction"
                widget: "text"
      - name: "tags"
        label: "Tags"
        file: "meta/tags.yml"
        description: "List of tags"
        fields:
          - name: tags
            label: Tags
            label_singular: "Tag"
            widget: list
            fields:
              - label: "Slug"
                name: "slug"
                widget: "string"
                hint: "The part of a URL identifies the tag"
              - label: "Display Name"
                name: "name"
                widget: "string"
                hint: "Tag name for displaying on the site"

  - name: "posts"
    label: "Posts"
    folder: "content/posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        dateFormat: "YYYY-MM-DD"
        timeFormat: false
      - label: Author
        name: "author"
        widget: relation
        collection: "meta"
        file: "authors"
        searchFields:
          - "authors.*.name"
        displayFields:
          - "authors.*.name"
        valueField: "authors.*.slug"
      - label: Tags
        label_singular: "Tag"
        name: "tags"
        widget: list
        summary: "{{fields.tag}}"
        field:
          label: Tag
          name: tag
          widget: relation
          collection: "meta"
          file: "tags"
          searchFields:
            - "tags.*.name"
          displayFields:
            - "tags.*.name"
          valueField: "tags.*.slug"
      - label: "Body"
        name: "body"
        widget: "markdown"

  - name: "pages"
    label: "Pages"
    folder: "content/pages/"
    extension: "mdx"
    format: "frontmatter"
    create: false
    delete: false
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Summary"
        name: "summary"
        widget: "string"
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Body"
        name: "body"
        required: false
        widget: "markdown"
      - label: "Galleries"
        name: "galleries"
        widget: "relation"
        collection: "galleries"
        search_fields: ['title']
        value_field: "{{slug}}"
        display_fields: ['title']
        required: false
        multiple: true

  - name: "galleries"
    label: "Galleries"
    label_singular: "Gallery"
    folder: "content/galleries/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{title}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Description"
        name: "description"
        widget: "string"
      - label: "Title Picture"
        name: "thumbnail"
        widget: "image"
      - label: "Photos"
        label_singular: "Photo"
        name: "photos"
        widget: "list"
        fields:
          - label: "Photo"
            name: "photo"
            widget: "image"

  - name: "footer"
    label: "Footer"
    delete: false
    files:
      - name: "spots"
        label: "Spots"
        file: "footer/spots.yml"
        description: "Current spots"
        fields:
          - label: "Date"
            name: "date"
            widget: "datetime"
            format: "DD/MM/YYYY"
            dateFormat: "DD/MM/YYYY"
            timeFormat: false
          - label: "Body"
            name: "body"
            widget: "markdown"
      - name: "address"
        label: "Address"
        file: "footer/address.yml"
        description: "Address data"
        fields:
          - label: "Body"
            name: "body"
            widget: "markdown"
